# NUMPY :-
NumPy, short for "Numerical Python," is a fundamental package in Python for numerical computations.

NumPy introduces the ndarray (N-dimensional array) data structure, which allows you to perform 
element-wise operations on arrays and matrices efficiently.

These operations are often much faster than using traditional Python lists due to NumPy's optimized implementation in C.

NumPy is a foundational library for many other scientific computing libraries in Python, such as SciPy, scikit-learn, and pandas.

# Numpy Arrays (ndarrays) ⇨
NumPy arrays are similar to Python lists but come with many advantages that make them essential for numerical and scientific computing.


Homogeneous Data Type.


Multidimensional Arrays.


Memory Efficiency.


Fast Element-Wise Operations.


Indexing 

# TO download Numpy Run the following command on your terminal.
pip install numpy

# Numpy Creating Arrays



In [1]:
import numpy as np

C:\Users\LENOVO\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\LENOVO\anaconda3\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
C:\Users\LENOVO\anaconda3\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
# Creating a 1D array
arr_1d = np.array([1, 2, 3])

# Creating a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])


In [3]:
print(arr_1d)

[1 2 3]


In [4]:
print(arr_2d)

[[1 2 3]
 [4 5 6]]


# 1.NumPy Array Creation Methods

In [5]:
# Importing NumPy and Pandas
import numpy as np
import pandas as pd
import random

In [6]:
# Method 1: Using np.array() with a Python list
array_from_list = np.array([1, 2, 3, 4, 5])
print("1. NumPy Array from Python List:")
print(array_from_list)

1. NumPy Array from Python List:
[1 2 3 4 5]


In [7]:
# Method 2: Using np.zeros() to create an array filled with zeros
zeros_array = np.zeros((2, 3))  # 2 rows, 3 columns
print("\n2. NumPy Zeros Array:")
print(zeros_array)


2. NumPy Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
# Method 3: Using np.ones() to create an array filled with ones
ones_array = np.ones((3, 2))  # 3 rows, 2 columns
print("\n3. NumPy Ones Array:")
print(ones_array)



3. NumPy Ones Array:
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [78]:
# Method 4: Using np.arange() to create an array with a range of values
range_array = np.arange(0, 10, 3)  # start, stop, step
print("\n4. NumPy Range Array:")
print(range_array)


4. NumPy Range Array:
[0 3 6 9]


In [10]:
# Method 5: Using np.linspace() to create an array with evenly spaced values
linspace_array = np.linspace(0, 1, 5)  # start, stop, number of points
print("\n5. NumPy Linspace Array:")
print(linspace_array)


5. NumPy Linspace Array:
[0.   0.25 0.5  0.75 1.  ]


In [11]:
# Method 6: Using np.random.rand() to create a random array with values between 0 and 1
random_array = np.random.rand(2, 3)  # 2 rows, 3 columns
print("\n6. NumPy Random Array:")
print(random_array)


6. NumPy Random Array:
[[0.45539785 0.63783781 0.80418844]
 [0.53562073 0.89465744 0.484881  ]]


In [80]:
# Method 7: Using np.eye() to create an identity matrix
identity_matrix = np.eye(13)  # 3x3 identity matrix
print("\n7. NumPy Identity Matrix:")
print(identity_matrix)


7. NumPy Identity Matrix:
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [13]:
# Method 8: Using np.random.randint() to create an array with random integers
randint_array = np.random.randint(1, 15, size=(2, 3))  # low, high, size
print("\n8. NumPy Random Integer Array:")
print(randint_array)


8. NumPy Random Integer Array:
[[ 9  6 14]
 [ 9 14  2]]


In [14]:
# Method 9: Using random.sample() from the random module to create a random list
random_list = random.sample(range(1, 10), 5)  # range, sample size
print("\n9. Random List using random.sample():")
print(random_list)


9. Random List using random.sample():
[9, 8, 2, 4, 1]


In [15]:
# Creating a Pandas Series from a NumPy Array
series_from_array = pd.Series(array_from_list, name='MySeries')
print("\n10. Pandas Series from NumPy Array:")
print(series_from_array)


10. Pandas Series from NumPy Array:
0    1
1    2
2    3
3    4
4    5
Name: MySeries, dtype: int32


# Mathmatical operation

In [42]:
 arr = np.array([1,2,3,4,15])

In [17]:
# Example 1: Sum
result_sum = np.sum(arr)
print("1. Sum:")
print(result_sum)

1. Sum:
15


In [18]:
# Example 2: Mean
result_mean = np.mean(arr)
print("\n2. Mean:")
print(result_mean)


2. Mean:
3.0


In [19]:
# Example 4: Square Root
result_sqrt = np.sqrt(arr)
print("\n4. Square Root:")
print(result_sqrt)


4. Square Root:
[1.         1.41421356 1.73205081 2.         2.23606798]


In [43]:
# Example 3: Standard Deviation
result_std = np.std(arr)
print("\n3. Standard Deviation:")
print(result_std)


3. Standard Deviation:
5.0990195135927845


In [21]:
# Example 5: Natural Logarithm
result_log = np.log(arr)
print("\n5. Natural Logarithm:")
print(result_log)


5. Natural Logarithm:
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [22]:
# Example 6: Exponential Function
result_exp = np.exp(arr)
print("\n6. Exponential Function:")
print(result_exp)


6. Exponential Function:
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


# Array Manipulation Methods:

In [45]:
# Reshape
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)
print("Reshaped Array:")
print(reshaped_arr)


Reshaped Array:
[[1 2 3]
 [4 5 6]]


In [46]:
arr

array([1, 2, 3, 4, 5, 6])

In [47]:
# Transpose
arr = np.array([[1, 2, 3], [4, 5, 6]])
transposed_arr = arr.T
print("\nTransposed Array:")
print(transposed_arr)


Transposed Array:
[[1 4]
 [2 5]
 [3 6]]


In [25]:
# Concatenate
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_arr = np.concatenate((arr1, arr2))
print("\nConcatenated Array:")
print(concatenated_arr)


Concatenated Array:
[1 2 3 4 5 6]


In [26]:
# Flatten
arr = np.array([[1, 2, 3], [4, 5, 6]])
flattened_arr = arr.flatten()
print("\nFlattened Array:")
print(flattened_arr)


Flattened Array:
[1 2 3 4 5 6]


In [27]:
# Unique
arr = np.array([1, 2, 2, 3, 4, 4, 5])
unique_values = np.unique(arr)
print("\nUnique Values:")
print(unique_values)


Unique Values:
[1 2 3 4 5]


In [60]:
# tolist
arr2 = np.array([1, 2, 3])
list_representation = arr.tolist()
print("\nList Representation:")
print(list_representation)


List Representation:
[1, 2, 3]


In [61]:
print((type),arr2)

<class 'type'> ['1' '2' 'ani' '3']


# Matrix and Vector Operations:

In [29]:
# Matrix Multiplication
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
matrix_product = np.dot(matrix1, matrix2)
print("\nMatrix Product:")
print(matrix_product)


Matrix Product:
[[19 22]
 [43 50]]


In [30]:
#First element (row 1, column 1):
   # (1 * 5) + (2 * 7) = 5 + 14 = 19


In [31]:
#Second element (row 1, column 2):
#(1 * 6) + (2 * 8) = 6 + 16 = 22

In [32]:
#Third element (row 2, column 1):
#(3 * 5) + (4 * 7) = 15 + 28 = 43


In [33]:
#Fourth element (row 2, column 2):
#(3 * 6) + (4 * 8) = 18 + 32 = 50


In [34]:
# Dot Product
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
dot_product = np.dot(vector1, vector2)
print("\nDot Product:")
print(dot_product)


Dot Product:
32


In [35]:
# Element-wise Multiplication (Hadamard Product)
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
elementwise_product = vector1 * vector2
print("\nElement-wise Multiplication:")
print(elementwise_product)


Element-wise Multiplication:
[ 4 10 18]


# Search Method

In [71]:
# argmax and argmin
arr22 = np.array([500,3, 1, 4, 1, 1, 2, 6, 0])
max_index = np.argmax(arr22)
min_index = np.argmin(arr22)
print("Index of Maximum:", max_index)
print("Index of Minimum:", min_index)

Index of Maximum: 0
Index of Minimum: 8


In [74]:
# where
arr = np.array([1, 2, 3, 4, 5, 6])
indices = np.where(arr > 5)
print("Indices where elements are greater than 2:", indices)


Indices where elements are greater than 2: (array([5], dtype=int64),)


In [75]:
# nonzero
arr = np.array([0, 3, 0, 5, 0])
nonzero_indices = np.nonzero(arr)
print("Indices of Nonzero Elements:", nonzero_indices)


Indices of Nonzero Elements: (array([1, 3], dtype=int64),)


# Sorting Methods:


In [81]:
# sort
arr = np.array([3, 1, 4])
sorted_arr = np.sort(arr)
print("Sorted Array:", sorted_arr)


Sorted Array: [1 3 4]


In [77]:
# argsort
arr = np.array([3, 1, 4])
indices_sorted = np.argsort(arr)
print("Indices that would sort the array:", indices_sorted)

Indices that would sort the array: [1 0 2]


In [41]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
indices = np.where(arr > 2)

values_greater_than_2 = arr[indices]

print("Values greater than 2:", values_greater_than_2)

Values greater than 2: [3 4 5]
